### ISSUE TITLE
Getting some message during sending report from VEN

### ISSUE THREAD

**Issue by chandank21** [OpenLEADR/openleadr-python#103]
PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  if obj.zone == 'local':
C:\python39\lib\site-packages\apscheduler\triggers\cron\__init__.py:159: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.localize(datetime(**values))
C:\python39\lib\site-packages\apscheduler\triggers\interval.py:66: PytzUsageWarning: The normalize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.normalize(next_fire_time)

**Comment by stan-janssen** [comment]
Yes, this is a recent issue due to a dependency on `pytz` in `apscheduler`, which runs all scheduling in openleadr. The maintainers of apscheduler addressed this in [this issue](https://github.com/agronholm/apscheduler/discussions/570).  You can safely ignore this warning for the moment. I'll look into whether manually installing tzlocal 2 (their recommendation) has any negative side-effects. You could do that in the meantime as well and report back if you can.
