### ISSUE TITLE
_perform_request should attempt to parse the body for valid XML if the HTTP status code is not 200 OK

### ISSUE THREAD

**Issue by jmuraca** [OpenLEADR/openleadr-python#22]
In client._perform_request function,
where if req.status != HTTPStatus.OK
return None, {}

If the response is OK (200), then parse the message payload and return the message type and payload

The issue here is that if the VTN returns an error for whatever reason, they should return an appropriate HTTP status code as well and use the response_description for the error message. 

The perform_request function is returning None if there is anything but a HTTP 200 OK, but rather should attempt to parse the XML from the VTN - as is done later in the client to get response_code and response_description in create_party_registration() for eaxmple.

**Comment by jmuraca** [comment]
I'll try checkout and commit tomorrow, but it seems to be that removing the "return None, {}" line from the "if response.status_code != requests.codes['ok']" conditional is enough to fall through to the messaging parser. May need to handle genuine non-xml body response, but that appears to be ok with the "The incoming message could not be parsed or validated" exception catch

**Comment by stan-janssen** [comment]
Thanks for your time and contribution! The error handling is indeed still a bit flimsy on both the client and the server side, so I appreciate you looking in to it.

The reason that OpenLEADR doesn't return even try to parse the response is any HTTP status code other than 200 is this part of the OpenADR specification:

> 9.1.5
HTTP Response Codes
The following HTTP status codes, defined in [RFC2616], are used in OpenADR:
> 
> **200 OK** – any response that the endpoint was able to handle completely and send a valid Open-
ADR response payload. This includes responses that may indicate an error at the application
level (e.g., ‘you gave me an invalid event ID.’) Errors that indicate a failure at the transport level
are handled by transport-level HTTP error codes:
> 
> **404 Not Found** – the VEN or VTN does not support the requested operation. The requestor must
not re-send the request.
>
> **406 Not Acceptable** – if a payload is sent that does not validate against the EI schema, or if a
request content-type is unsupported. The requestor must not re-send the request without first
modifying it.
>
> **501 Not Implemented** – if any request is made with an unsupported HTTP method. The reques-
tor must not re-send the request without fixing the HTTP method.
>
> **503 Service Unavailable** – indicates that the server is temporarily unavailable, possibly due to
inability to handle the current request load. This error in particular must indicate to the requestor
that it must execute quiesce logic in order to not put further strain on the server. The requestor
must retry the request after the proper quiesce period.
> 
> **500 Internal Server Error** – undefined or unexpected server error. The requestor may retry the
request after a quiesce period.
> 
> For all error (non-200) codes, the content body of the response is undefined. The server may
choose to send some informational message in the response, but the requestor is not obligated
to parse or understand it.
>
> All application-level error conditions are conveyed through the status code element of oadrRe-
sponse payload.

Especially this part:

> For all error (non-200) codes, the content body of the response is undefined. The server may
choose to send some informational message in the response, but the requestor is not obligated
to parse or understand it.

I don't think that the VTN would / should ever send a valid OpenADR response if it is not carrying a 200 payload, which means that validation will always fail. This is why OpenLEADR simply logs whatever it receives and does not try to interpret the result.

Are you connecting to a VTN that does this? I'd be interested to know which one it is to look at it.

**Comment by jmuraca** [comment]
I think this is ambiguous. Agree the response_code and response_description fields should hold this information, but my interpretation has been that the HTTP status code is reflected with the codes too. I think this should be the case for HTTP comms as standard.

This is reflected at a VTN which I wrote (happy to chat off list for this). I will check with other VTN implementations, as well as the test harness.

**Comment by stan-janssen** [comment]
The application error codes defined in the OpenADR standard range from 450 to 459 for "compliance errors" and from 460 to 469 for "deployment errors". These error codes are not valid (or at least: unspecified) HTTP error codes in the HTTP specification, with the exception of 451 (Unavailable for Legal Reasons), which is a [proposed addition to the HTTP standard](https://tools.ietf.org/html/rfc7725) (in OpenADR, status code 451 means "Not Allowed (changing an event in the past)").

To me, the first part of the above-quoted part of the manual is unambiguous:

> 200 OK – any response that the endpoint was able to handle completely and send a valid Open-
ADR response payload. This includes responses that may indicate an error at the application
level (e.g., ‘you gave me an invalid event ID.’) Errors that indicate a failure at the transport level
are handled by transport-level HTTP error codes.

I tested it against the Nebland OADR VTN (which was open sourced years ago), and it returns for instance a HTTP 200 together with application error code 452 (Invalid ID) when I attempt to connect a VEN with an unknown venID or venName.

Let me know what the test harness says!

**Comment by jmuraca** [comment]
I tested with SCE and PG&E in California and both of these return a HTTP 401 unauth error. 

```
curl -i -X POST "https://www.sce.openadr.com/vtn/OpenADR2/Simple/EiEvent"
HTTP/1.1 401 Unauthorized
Date: Sat, 21 Nov 2020 20:31:03 GMT
Server: Apache
Expires: 0
Cache-Control: no-cache, no-store, must-revalidate
X-Powered-By: Undertow/1
Pragma: no-cache
WWW-Authenticate: Basic realm="PSS2WS"
Content-Length: 71
Content-Type: text/html;charset=UTF-8

<html><head><title>Error</title></head><body>Unauthorized</body></html>
```

```
curl -i -X POST "https://pgeqa.trcseeload.com/SEEload/OpenADR2/Simple/EiEvent"
HTTP/1.1 401 Unauthorized
Server: GlassFish Server Open Source Edition  4.1.1
X-Powered-By: Servlet/3.1 JSP/2.3 (GlassFish Server Open Source Edition  4.1.1  Java/Oracle Corporation/1.8)
WWW-Authenticate: Basic realm=""
Content-Language:
Content-Type: text/html
Date: Sat, 21 Nov 2020 20:31:59 GMT
Content-Length: 1094

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>GlassFish Server Open Source Edition  4.1.1  - Error report</title><style type="text/css"><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 401 - Unauthorized</h1><hr/><p><b>type</b> Status report</p><p><b>message</b>Unauthorized</p><p><b>description</b>This request requires HTTP authentication.</p><hr/><h3>GlassFish Server Open Source Edition  4.1.1 </h3></body></html>
```

**Comment by jmuraca** [comment]
I don't see any issue with the OpenLeadr VEN code parsing the HTTP status codes which are not 200 OK. 
I could see the hesitation on the VTN side of the OpenLeadr project, but still suggest the best practice was be to return the most descriptive HTTP status code possible.

**Comment by stan-janssen** [comment]
Well, they return 401 with HTML content; there is no OpenADR message in that response. 

My guess is that their implementation considers a https request without a client side certificate a transport layer error, which is why it never hits the OpenADR application (evidenced by the HTML output that is returned).

Can you try to connect to that VTN with a valid authorization but with some invalid data in your message?

The reason for not assigning HTTP status codes is that *transport level* failures are communicated using HTTP status codes. OpenADR is not even involved in that part of the communication. Once we reach OpenADR, HTTP is merely a transport method for messages; as long as the message transfer was successful and the messages reach the OpenADR applications, the transport part was successful and the transport-level status codes should be nothing other than "200 OK".

The reason for the VEN not parsing *transport level* status codes is that there is nothing that OpenLEADR could do if transport fails; there should not be any OpenADR content in the response if the transport was not successful, because we never reached the other side's OpenADR application. 

This is how the OpenADR protocol was defined and I don't want to change this in my jmplementation.

Please try the SCE VTNs with a valid connection and let me know, and let me know what the test harness says.

**Comment by jmuraca** [comment]
With valid VEN_ID and username/pass for basic auth, response is good
![image](https://user-images.githubusercontent.com/1421873/99888755-e72de200-2c03-11eb-8a58-8a3a51d88952.png)

With invalid ven_id, username and pass is the same, response is 401 unauth at HTTP
![image](https://user-images.githubusercontent.com/1421873/99888813-4ab80f80-2c04-11eb-840a-daa7b1405261.png)

**Comment by stan-janssen** [comment]
Was there an OpenADR response to that last message? I only see the request.

**Comment by jmuraca** [comment]
I reverted to Postman and used no request ID to force an error.

Returns 200 HTTP status but 400 response code in body
![image](https://user-images.githubusercontent.com/1421873/99913699-df2a7c80-2cad-11eb-8dee-5beb206ae2cb.png)

I will still try on another VTN or two, but this looks like a good result.

**Comment by stan-janssen** [comment]
So they also send HTTP 200 together with an openADR status code, which is how it should be according to the spec. They do, however, use a non-existing OpenADR error code (400), I believe.

**Comment by stan-janssen** [comment]
Since there are no updates to this, I'm going to close this issue. I have not seen an instance where a VTN sends a non-200 HTTP response code with any useful OpenADR content, which is consistent with my interpretation of the spec as well.
