### ISSUE TITLE
openleadr 0.5.10 Python module: cannot import name 'OpenADRCLient'

### ISSUE THREAD

**Issue by armtir** [OpenLEADR/openleadr-python#29]
Client example doesn't work: [https://openleadr.org/docs/](https://openleadr.org/docs/)
All requirements have been met. This error occures on Linux as well as on Windows.

`ImportError: cannot import name 'OpenADRClient' from partially initialized module 'openleadr' (most likely due to a circular import)`

**Comment by stan-janssen** [comment]
That's odd.

First things first: I've tested it on Windows like this.

1. python -m pip install openleadr
2. python -m pip list gives this output:

```
C:\Users\Stan>pip list
Package           Version
----------------- ---------
aiohttp           3.7.3
APScheduler       3.6.3
async-timeout     3.0.1
attrs             20.3.0
certifi           2020.11.8
cffi              1.14.4
chardet           3.0.4
cryptography      3.2.1
eight             1.0.0
future            0.18.2
idna              2.10
Jinja2            2.11.2
lxml              4.6.2
MarkupSafe        1.1.1
multidict         5.0.2
openleadr         0.5.10
pip               20.2.3
pycparser         2.20
pyOpenSSL         19.1.0
pytz              2020.4
setuptools        49.2.1
signxml-openadr   2.9.1
six               1.15.0
typing-extensions 3.7.4.3
tzlocal           2.1
xmltodict         0.12.0
yarl              1.6.3
WARNING: You are using pip version 20.2.3; however, version 20.3 is available.
You should consider upgrading via the 'c:\users\stan\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.
```

3. Create a file `example.py` with the following contents (copy-pasted from the Client example in the docs):

```python
from openleadr import OpenADRClient
import asyncio

async def main():
    client = OpenADRClient(ven_name="Device001",
                           vtn_url="http://localhost:8080/OpenADR2/Simple/2.0b")
    client.add_handler('on_event', handle_event)
    await client.run()

async def handle_event(event):
    """
    This coroutine will be called
    when there is an event to be handled.
    """
    print("There is an event!")
    print(event)
    # Do something to determine whether to Opt In or Opt Out
    return 'optIn'

loop = asyncio.get_event_loop()
loop.create_task(main())
loop.run_forever()

```

4. Run the example: `C:\Users\Stan>python example.py`

Gives the following output:
```
Could not connect to server with URL http://localhost:8080/OpenADR2/Simple/2.0b:
ClientConnectorError: Cannot connect to host localhost:8080 ssl:default [De netwerkverbinding is geweigerd door de externe computer]
No VEN ID received from the VTN, aborting.
```

Which is what we expect. No ImportErrors.

On linux, I get the same thing. I've not been able to reproduce the problem here, so I'd like your help to at least reproduce the issue so I can fix it.

Some things to check:

- Do you have another file called `openleadr.py` perhaps, that the import is trying to get something from?
- Are you using a virtual environment? If so, is openleadr indeed installed in that venv and is the python interpreter that your are running the example from looking in the right place?

I hope you can give me some more info. Thanks.

**Comment by armtir** [comment]
Thanks for your reply.
An `openleadr.py` has caused the problem.

**Comment by stan-janssen** [comment]
Yes, that can be a real head scratcher, glad it was an easy fix! Thanks.
