### ISSUE TITLE
How to deal the error when run (./python_env/bin/pip3 install -e .) in the Readme.md

### ISSUE THREAD

**Issue by 18611429192** [OpenLEADR/openleadr-python#34]
When I fellow the Readme.md to run the ./python_env/bin/pip3 install -e .  , i meet a error. 
![error](https://user-images.githubusercontent.com/49744753/102009402-24ecd900-3d72-11eb-90c2-d116fccae08d.png)

My os is Ubuntu18.04 and version of Python is Python3.9.1.
I also try the Python3.7.9 and Python 3.8.6, but the error is same. 
I don't know how to cope the error.

**Comment by stan-janssen** [comment]
I assume you've compiled Python 3.9 from source, since it is not available in the Ubuntu 18.04 repositories.

Python is complaining that the `_ctypes` module is not found. CTypes is only compiled with python if you have `libffi-dev` is installed *before* compiling python.

So to add support for it should be something like:

```
sudo apt update
sudo apt install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget libbz2-dev
```

Then go to the Python-3.9.1 source directory, and do:

```
./configure
make
sudo make install
```

Then, remove your virtual environment and re-create it, and you should be good to go.

Ubuntu 18.04 does provide an apt-package for python 3.7 and 3.8, which I believe should have support for _ctypes built in.

If you did not compile Python 3.9 from source yourself, how did you install it?

**Comment by 18611429192** [comment]
I used the above method, there are still a variety of errors.
I gave up Ubuntu 18.04 and used Ubuntu 20.04, and everything was OK.

**Comment by stan-janssen** [comment]
I'm using this myself on Ubuntu 18.04, but it sounds like your Python installation was not OK. Glad you got it working on Ubuntu 20!

**Comment by 18611429192** [comment]
I thought you were using Ubuntu 20.04, because when I install those libraries, Ubuntu 18.04 always reminds me that I rely on the wrong version. Later, I changed to Ubuntu 20.04 and installed those libraries smoothly. After updating pip in virtual environment, I passed the test successfully.Anyway, thank you for your help.
