### ISSUE TITLE
ven_lookup(ven_id) on server tips

### ISSUE THREAD

**Issue by bbartling** [OpenLEADR/openleadr-python#68]
Would anyone be able to give me a tip on how to incorporate a callable `fingerprint_lookup` on the `OpenADRServer` script?

For example in the Server documentation, for the [You should implement the following handler](https://openleadr.org/docs/server.html#:~:text=you%20should%20implement%20the%20following%20handlers)s with a function for `ven_lookup`

If I had something like this below to experiment with:

```
def ven_lookup(ven_id):
     
     ven_info = {'ven1_info':
          {'ven_id': 'ven_id_123',
          'ven_name': 'ven123',
          'fingerprint': '7F:7F:7F:7F:7F:7F:7F:7F:7F:7F',
          'registration_id': 'reg_id_123'},

          'ven2_info':
          {'ven_id': 'ven_id_321',
          'ven_name': 'ven321',
          'fingerprint': 'G3:G3:G3:G3:G3:G3:G3:G3:G3:G3',
          'registration_id': 'reg_id_321'}
}
     
     look_up = [ven for ven in ven_info.values() if ven['ven_id'] == ven_id]
     if look_up != []:
         return look_up[0]
     else:
         return {}
```

How could I incorporate the ven_lookup function above into the `fingerprint_lookup=fingerprint_lookup`?

```
server = OpenADRServer(vtn_id='MyVTN',
                       cert='/path/to/cert.pem',
                       key='/path/to/private/key.pem',
                       passphrase='mypassphrase',
                       fingerprint_lookup=fingerprint_lookup)
```

Any tips trying to incorporate that last bullet point greatly appreciated, I am still trying to wrap my head around this:

- ven_lookup(ven_id): a function that returns a dict with the ‘ven_name’, 'ven_id', 'fingerprint' and 'registration_id' for the given ven_id (see below.). This is used to automatically reject requests from VENs that the VTN does not know, and to authenticate the VENs message signatures.

**Comment by stan-janssen** [comment]
An example ven_lookup function would be this:

```python3
#vtn.py

# Define your VENS somewhere
VENS = {"ven_id_123": {"ven_name": "ven_name_123", "registration_id": "reg_id_123", "fingerprint": "00:11:22:33:44:55:66:77:88:99"},
        "ven_id_456": {"ven_name": "ven_name_456", "registration_id": "reg_id_456", "fingerprint": "AA:BB:CC:DD:EE:FF:00:11:22:33"}}


def ven_lookup_function(ven_id):
    if ven_id in VENS:
        return VENS[ven_id]
    else:
        return False

server = OpenADRServer(vtn_id='MyVTN',
                       cert='/path/to/cert.pem',
                       key='/path/to/private/key.pem',
                       passphrase='mypassphrase',
                       ven_lookup=ven_lookup_function)
```

The fingerprint that the VTN has is the fingerprint that the VEN client tells you to "deliver to the VTN". Either the VTN already knowns your fingerprint because they supplied you with the certificate, or you e-mail the fingerprint to them or deliver it through some other means (this is outside the OpenADR messages).

Usually, when you are building a larger application, the ven information would not live in a simple dectionary, but rather in a database. Instead of the `if ven_id in VENS` line, you would query your database to look up the ven_id in there.

Also: if you provide the `ven_lookup` function to your VTN, you don't need the `fingerprint_lookup`. The `fingerprint_lookup` was an older idea and it will be removed in the future, because `ven_lookup` already encompasses it.

**Comment by bbartling** [comment]
Thank you!
